### PR TITLE
Fast read last final fix attempt

### LINKED ISSUE #56: CGI-08: Remove dead code from CGI.hpp and CGI.cpp
- [ ] Remove unused constant POLL_INTERVAL_MS from [CGI.hpp](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)
- [ ] Remove [_is_complete](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) field — [setComplete()](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) is called but [_is_complete](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) is never read by any logic
- [ ] Remove setting [_error_type](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) in child process after [fork()](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) — child memory is not shared with parent, these assignments have no effect

### PR DESCRIPTION
**Pull request by SmVynt**
This pull request consists of several improvements and bug fixes to the server's core, focusing on CGI handling, request processing, connection management, and configuration defaults. The most significant changes are grouped below:

**CGI Handling Improvements:**

* Refactored the `CGIexecutor` and `CGIconfig` classes to remove direct storage of POST data and instead track only the POST data size, simplifying CGI input management. The `setPostData` method is replaced with `setPostDataSize`.
* Added `detachPipeFd` method to `CGIexecutor` for better management of pipe file descriptors during CGI execution and cleanup.
* Improved CGI child process management by checking script existence and executability only for non-POST requests, and enhanced error mapping/logging.

**Request and Response Processing:**

* Added support for handling HTTP `Expect: 100-continue` by tracking the expectation in the `Request` class, updating the `FDMetadata` struct, and sending the 100 Continue response at the appropriate time in the connection lifecycle.
* Increased the receive buffer size from 4KB to 64KB for improved throughput when handling large requests. 

**Connection and FD Management:**

* Improved robustness in file descriptor (FD) management by adding a `removeFDNoClose` method to remove FDs from tracking without closing them, and updating `closeConnection` and poll event handling to better manage lost CGI pipes and invalid FDs. 
* Enhanced error handling for client disconnections and poll errors by ensuring proper cleanup of resources and avoiding double-closing of FDs. 

**Configuration Defaults:**

* Set default values for `ServerConfig` struct members (e.g., `port = 0`, `client_max_body_size = 1MB`, `client_timeout = 60`, `session_timeout = 300`). 

**Issues to close**
#56

### CODE REVIEW

**Review by Vspaceman11 — COMMENTED** [review]
Nice work!

File: includes/Cluster.hpp [hunk 1]
```diff
@@ -25,7 +25,7 @@
 
 class CGIexecutor;
 // Default value
-static const size_t			RECV_BUFFER_SIZE		= 4096;
+static const size_t			RECV_BUFFER_SIZE		= 65536;
```
Comment (SuPuHe) [inline includes/Cluster.hpp:28]: we should move it later in cpp file

File: includes/Config.hpp [hunk 2]
```diff
@@ -24,14 +24,14 @@ struct Location {
...
 	std::string host;
 	std::vector<std::string> server_names;
-	unsigned long client_max_body_size;
+	unsigned long client_max_body_size = 1048576;
 	std::map<int, std::string> error_pages;
 	std::vector<Location> locations;
-	int	client_timeout;
-	int	session_timeout;
+	int	client_timeout = 60;
+	int	session_timeout = 300;
```
Comment (SuPuHe) [inline includes/Config.hpp:34]: also here we should move it later in cpp file

File: srcs/core/Cluster.cpp [hunk 3]
```diff
@@ -477,6 +530,15 @@ void Cluster::updatePollEvents(int fd, short events)
...
 	FDMetadata& data = _fd_table.at(fd);
+
+	if (data.needs_continue) {
+		static const char cont[] = "HTTP/1.1 100 Continue\r\n\r\n";
+		send(fd, cont, sizeof(cont) - 1, MSG_NOSIGNAL);
+		data.needs_continue = false;
+		updatePollEvents(fd, POLLIN);
+		return false;
+	}
+
```
Comment (SuPuHe) [inline srcs/core/Cluster.cpp:541]: idk if we need that

File: srcs/parser/Request.cpp [hunk 4]
```diff
@@ -160,7 +186,7 @@ void	Request::parseRequestLine(const std::string &line){
 	}
 	if (method != "GET" && method != "POST" && method != "DELETE" && method != "HEAD"){
 		_state = ERROR;
-		_error_code = 405;
+		_error_code = 501;
```
Comment (SuPuHe) [inline srcs/parser/Request.cpp:189]: ok?

File: srcs/core/Cluster.cpp (hunk 3 above)
Comment (SmVynt) [reply srcs/core/Cluster.cpp:541]: This fix turned out to be very small and not so invasive as i originally thought.

**Review by SuPuHe — APPROVED** [review]
everything is nice. Just need to move declaration from hpp to cpp
